### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fyn-dev** [cdimascio/generator-express-no-stress-typescript#1]
I just used 

> yo express-no-stress-typescript my-app

then 

> cd my-app
> npm run dev

and at the end got this:

```
fyn@1.0.0 dev /home/user/my-app
> node build.js && backpack dev | bunyan -o 'short'


[at-loader] Using typescript@2.6.2 from typescript and "tsconfig.json" from /home/user/my-app/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 2 errors
 ERROR  Failed to compile with 2 errors13:25:20

 error  

[at-loader] ./server/common/server.ts:32:10 
    TS2322: Type 'string' is not assignable to type 'number'.

 error  

[at-loader] ./server/index.ts:7:11 
    TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

module.js:538
    throw err;
    ^

Error: Cannot find module '/home/user/my-app/build/main.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by cdimascio** [comment]
@fyn-dev thanks for this issue. 
I just delivered a fix in the new version. 
I will post the release notes in 'Release' shortly
